//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("entity", "Modulos_Formularios_FK1", "mModulos", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DAO.mModulos), "Formularios", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAO.Formularios), true)]

#endregion

namespace DAO
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ctxModulos : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ctxModulos object using the connection string found in the 'ctxModulos' section of the application configuration file.
        /// </summary>
        public ctxModulos() : base("name=ctxModulos", "ctxModulos")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ctxModulos object.
        /// </summary>
        public ctxModulos(string connectionString) : base(connectionString, "ctxModulos")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ctxModulos object.
        /// </summary>
        public ctxModulos(EntityConnection connection) : base(connection, "ctxModulos")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<mModulos> entityModulos
        {
            get
            {
                if ((_entityModulos == null))
                {
                    _entityModulos = base.CreateObjectSet<mModulos>("entityModulos");
                }
                return _entityModulos;
            }
        }
        private ObjectSet<mModulos> _entityModulos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Formularios> Formularios
        {
            get
            {
                if ((_Formularios == null))
                {
                    _Formularios = base.CreateObjectSet<Formularios>("Formularios");
                }
                return _Formularios;
            }
        }
        private ObjectSet<Formularios> _Formularios;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the entityModulos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToentityModulos(mModulos mModulos)
        {
            base.AddObject("entityModulos", mModulos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Formularios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFormularios(Formularios formularios)
        {
            base.AddObject("Formularios", formularios);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="entity", Name="Formularios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Formularios : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Formularios object.
        /// </summary>
        /// <param name="idFormulario">Initial value of the idFormulario property.</param>
        /// <param name="xID">Initial value of the xID property.</param>
        /// <param name="xName">Initial value of the xName property.</param>
        /// <param name="stSingleton">Initial value of the stSingleton property.</param>
        /// <param name="xScope">Initial value of the xScope property.</param>
        /// <param name="xType">Initial value of the xType property.</param>
        /// <param name="stAtivo">Initial value of the stAtivo property.</param>
        public static Formularios CreateFormularios(global::System.Int32 idFormulario, global::System.String xID, global::System.String xName, global::System.Boolean stSingleton, global::System.String xScope, global::System.String xType, global::System.Boolean stAtivo)
        {
            Formularios formularios = new Formularios();
            formularios.idFormulario = idFormulario;
            formularios.xID = xID;
            formularios.xName = xName;
            formularios.stSingleton = stSingleton;
            formularios.xScope = xScope;
            formularios.xType = xType;
            formularios.stAtivo = stAtivo;
            return formularios;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idFormulario
        {
            get
            {
                return _idFormulario;
            }
            set
            {
                if (_idFormulario != value)
                {
                    OnidFormularioChanging(value);
                    ReportPropertyChanging("idFormulario");
                    _idFormulario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idFormulario");
                    OnidFormularioChanged();
                }
            }
        }
        private global::System.Int32 _idFormulario;
        partial void OnidFormularioChanging(global::System.Int32 value);
        partial void OnidFormularioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idModulo
        {
            get
            {
                return _idModulo;
            }
            set
            {
                OnidModuloChanging(value);
                ReportPropertyChanging("idModulo");
                _idModulo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idModulo");
                OnidModuloChanged();
            }
        }
        private Nullable<global::System.Int32> _idModulo;
        partial void OnidModuloChanging(Nullable<global::System.Int32> value);
        partial void OnidModuloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String xID
        {
            get
            {
                return _xID;
            }
            set
            {
                OnxIDChanging(value);
                ReportPropertyChanging("xID");
                _xID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("xID");
                OnxIDChanged();
            }
        }
        private global::System.String _xID;
        partial void OnxIDChanging(global::System.String value);
        partial void OnxIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String xName
        {
            get
            {
                return _xName;
            }
            set
            {
                OnxNameChanging(value);
                ReportPropertyChanging("xName");
                _xName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("xName");
                OnxNameChanged();
            }
        }
        private global::System.String _xName;
        partial void OnxNameChanging(global::System.String value);
        partial void OnxNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean stSingleton
        {
            get
            {
                return _stSingleton;
            }
            set
            {
                OnstSingletonChanging(value);
                ReportPropertyChanging("stSingleton");
                _stSingleton = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("stSingleton");
                OnstSingletonChanged();
            }
        }
        private global::System.Boolean _stSingleton;
        partial void OnstSingletonChanging(global::System.Boolean value);
        partial void OnstSingletonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String xScope
        {
            get
            {
                return _xScope;
            }
            set
            {
                OnxScopeChanging(value);
                ReportPropertyChanging("xScope");
                _xScope = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("xScope");
                OnxScopeChanged();
            }
        }
        private global::System.String _xScope;
        partial void OnxScopeChanging(global::System.String value);
        partial void OnxScopeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String xType
        {
            get
            {
                return _xType;
            }
            set
            {
                OnxTypeChanging(value);
                ReportPropertyChanging("xType");
                _xType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("xType");
                OnxTypeChanged();
            }
        }
        private global::System.String _xType;
        partial void OnxTypeChanging(global::System.String value);
        partial void OnxTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean stAtivo
        {
            get
            {
                return _stAtivo;
            }
            set
            {
                OnstAtivoChanging(value);
                ReportPropertyChanging("stAtivo");
                _stAtivo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("stAtivo");
                OnstAtivoChanged();
            }
        }
        private global::System.Boolean _stAtivo;
        partial void OnstAtivoChanging(global::System.Boolean value);
        partial void OnstAtivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String xObservacao
        {
            get
            {
                return _xObservacao;
            }
            set
            {
                OnxObservacaoChanging(value);
                ReportPropertyChanging("xObservacao");
                _xObservacao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("xObservacao");
                OnxObservacaoChanged();
            }
        }
        private global::System.String _xObservacao;
        partial void OnxObservacaoChanging(global::System.String value);
        partial void OnxObservacaoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("entity", "Modulos_Formularios_FK1", "mModulos")]
        public mModulos Modulos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mModulos>("entity.Modulos_Formularios_FK1", "mModulos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mModulos>("entity.Modulos_Formularios_FK1", "mModulos").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<mModulos> ModulosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<mModulos>("entity.Modulos_Formularios_FK1", "mModulos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<mModulos>("entity.Modulos_Formularios_FK1", "mModulos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="entity", Name="mModulos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class mModulos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new mModulos object.
        /// </summary>
        /// <param name="idModulo">Initial value of the idModulo property.</param>
        /// <param name="xNome">Initial value of the xNome property.</param>
        /// <param name="xNameSpaceCamada">Initial value of the xNameSpaceCamada property.</param>
        public static mModulos CreatemModulos(global::System.Int32 idModulo, global::System.String xNome, global::System.String xNameSpaceCamada)
        {
            mModulos mModulos = new mModulos();
            mModulos.idModulo = idModulo;
            mModulos.xNome = xNome;
            mModulos.xNameSpaceCamada = xNameSpaceCamada;
            return mModulos;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idModulo
        {
            get
            {
                return _idModulo;
            }
            set
            {
                if (_idModulo != value)
                {
                    OnidModuloChanging(value);
                    ReportPropertyChanging("idModulo");
                    _idModulo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idModulo");
                    OnidModuloChanged();
                }
            }
        }
        private global::System.Int32 _idModulo;
        partial void OnidModuloChanging(global::System.Int32 value);
        partial void OnidModuloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String xNome
        {
            get
            {
                return _xNome;
            }
            set
            {
                OnxNomeChanging(value);
                ReportPropertyChanging("xNome");
                _xNome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("xNome");
                OnxNomeChanged();
            }
        }
        private global::System.String _xNome;
        partial void OnxNomeChanging(global::System.String value);
        partial void OnxNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String xNameSpaceCamada
        {
            get
            {
                return _xNameSpaceCamada;
            }
            set
            {
                OnxNameSpaceCamadaChanging(value);
                ReportPropertyChanging("xNameSpaceCamada");
                _xNameSpaceCamada = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("xNameSpaceCamada");
                OnxNameSpaceCamadaChanged();
            }
        }
        private global::System.String _xNameSpaceCamada;
        partial void OnxNameSpaceCamadaChanging(global::System.String value);
        partial void OnxNameSpaceCamadaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("entity", "Modulos_Formularios_FK1", "Formularios")]
        public EntityCollection<Formularios> Formularios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Formularios>("entity.Modulos_Formularios_FK1", "Formularios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Formularios>("entity.Modulos_Formularios_FK1", "Formularios", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
