//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace DAO
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ctxFormularios : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ctxFormularios object using the connection string found in the 'ctxFormularios' section of the application configuration file.
        /// </summary>
        public ctxFormularios() : base("name=ctxFormularios", "ctxFormularios")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ctxFormularios object.
        /// </summary>
        public ctxFormularios(string connectionString) : base(connectionString, "ctxFormularios")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ctxFormularios object.
        /// </summary>
        public ctxFormularios(EntityConnection connection) : base(connection, "ctxFormularios")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<vwFormularios> vwFormularios
        {
            get
            {
                if ((_vwFormularios == null))
                {
                    _vwFormularios = base.CreateObjectSet<vwFormularios>("vwFormularios");
                }
                return _vwFormularios;
            }
        }
        private ObjectSet<vwFormularios> _vwFormularios;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the vwFormularios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovwFormularios(vwFormularios vwFormularios)
        {
            base.AddObject("vwFormularios", vwFormularios);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PROD_MODULOSModel", Name="vwFormularios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vwFormularios : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new vwFormularios object.
        /// </summary>
        /// <param name="xNome">Initial value of the xNome property.</param>
        /// <param name="xID">Initial value of the xID property.</param>
        /// <param name="xName">Initial value of the xName property.</param>
        /// <param name="xType">Initial value of the xType property.</param>
        /// <param name="stSingleton">Initial value of the stSingleton property.</param>
        /// <param name="xScope">Initial value of the xScope property.</param>
        /// <param name="stAtivo">Initial value of the stAtivo property.</param>
        public static vwFormularios CreatevwFormularios(global::System.String xNome, global::System.String xID, global::System.String xName, global::System.String xType, global::System.Boolean stSingleton, global::System.String xScope, global::System.Boolean stAtivo)
        {
            vwFormularios vwFormularios = new vwFormularios();
            vwFormularios.xNome = xNome;
            vwFormularios.xID = xID;
            vwFormularios.xName = xName;
            vwFormularios.xType = xType;
            vwFormularios.stSingleton = stSingleton;
            vwFormularios.xScope = xScope;
            vwFormularios.stAtivo = stAtivo;
            return vwFormularios;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String xNome
        {
            get
            {
                return _xNome;
            }
            set
            {
                if (_xNome != value)
                {
                    OnxNomeChanging(value);
                    ReportPropertyChanging("xNome");
                    _xNome = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("xNome");
                    OnxNomeChanged();
                }
            }
        }
        private global::System.String _xNome;
        partial void OnxNomeChanging(global::System.String value);
        partial void OnxNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String xID
        {
            get
            {
                return _xID;
            }
            set
            {
                if (_xID != value)
                {
                    OnxIDChanging(value);
                    ReportPropertyChanging("xID");
                    _xID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("xID");
                    OnxIDChanged();
                }
            }
        }
        private global::System.String _xID;
        partial void OnxIDChanging(global::System.String value);
        partial void OnxIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String xName
        {
            get
            {
                return _xName;
            }
            set
            {
                if (_xName != value)
                {
                    OnxNameChanging(value);
                    ReportPropertyChanging("xName");
                    _xName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("xName");
                    OnxNameChanged();
                }
            }
        }
        private global::System.String _xName;
        partial void OnxNameChanging(global::System.String value);
        partial void OnxNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String xType
        {
            get
            {
                return _xType;
            }
            set
            {
                if (_xType != value)
                {
                    OnxTypeChanging(value);
                    ReportPropertyChanging("xType");
                    _xType = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("xType");
                    OnxTypeChanged();
                }
            }
        }
        private global::System.String _xType;
        partial void OnxTypeChanging(global::System.String value);
        partial void OnxTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean stSingleton
        {
            get
            {
                return _stSingleton;
            }
            set
            {
                if (_stSingleton != value)
                {
                    OnstSingletonChanging(value);
                    ReportPropertyChanging("stSingleton");
                    _stSingleton = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("stSingleton");
                    OnstSingletonChanged();
                }
            }
        }
        private global::System.Boolean _stSingleton;
        partial void OnstSingletonChanging(global::System.Boolean value);
        partial void OnstSingletonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String xScope
        {
            get
            {
                return _xScope;
            }
            set
            {
                if (_xScope != value)
                {
                    OnxScopeChanging(value);
                    ReportPropertyChanging("xScope");
                    _xScope = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("xScope");
                    OnxScopeChanged();
                }
            }
        }
        private global::System.String _xScope;
        partial void OnxScopeChanging(global::System.String value);
        partial void OnxScopeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String xObservacao
        {
            get
            {
                return _xObservacao;
            }
            set
            {
                OnxObservacaoChanging(value);
                ReportPropertyChanging("xObservacao");
                _xObservacao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("xObservacao");
                OnxObservacaoChanged();
            }
        }
        private global::System.String _xObservacao;
        partial void OnxObservacaoChanging(global::System.String value);
        partial void OnxObservacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idModulo
        {
            get
            {
                return _idModulo;
            }
            set
            {
                OnidModuloChanging(value);
                ReportPropertyChanging("idModulo");
                _idModulo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idModulo");
                OnidModuloChanged();
            }
        }
        private Nullable<global::System.Int32> _idModulo;
        partial void OnidModuloChanging(Nullable<global::System.Int32> value);
        partial void OnidModuloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean stAtivo
        {
            get
            {
                return _stAtivo;
            }
            set
            {
                if (_stAtivo != value)
                {
                    OnstAtivoChanging(value);
                    ReportPropertyChanging("stAtivo");
                    _stAtivo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("stAtivo");
                    OnstAtivoChanged();
                }
            }
        }
        private global::System.Boolean _stAtivo;
        partial void OnstAtivoChanging(global::System.Boolean value);
        partial void OnstAtivoChanged();

        #endregion

    
    }

    #endregion

    
}
